{% set name = "django-vite" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-vite-{{ version }}.tar.gz
  sha256: c59b3bbd85501bc1faf63c500df66542abed2951cfa10dfbf8be8ecf229f7652

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django >=1.11

test:
  imports:
    - django_vite
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MrBin99/django-vite
  summary: Integration of ViteJS in a Django project.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
